<?php $eloquaForm = array (
  'action' => 'https://s1851.t.eloqua.com/e/f2',
  'fields' =>
  array (
    'emailAddress' =>
    array (
      'type' => 'email',
      'displayName' => 'Email Address',
      'apiName' => 'C_EmailAddress',
    ),
    'firstName' =>
    array (
      'type' => 'text',
      'displayName' => 'First Name',
      'apiName' => 'C_FirstName',
    ),
    'lastName' =>
    array (
      'type' => 'text',
      'displayName' => 'Last Name',
      'apiName' => 'C_LastName',
    ),
    'company' =>
    array (
      'type' => 'text',
      'displayName' => 'Company',
      'apiName' => 'C_Company',
    ),
    'institution' =>
    array (
      'type' => 'text',
      'displayName' => 'Institution\'s Name',
      'apiName' => 'C_Company',
    ),
    'businessPhone' =>
    array (
      'type' => 'tel',
      'displayName' => 'Business Phone',
      'apiName' => 'C_BusPhone',
    ),
    'country' =>
    array (
      'type' => 'select',
      'displayName' => 'Country',
      'apiName' => 'C_Country',
      'options' =>
      array (
        '' => '--------------',
        'US' => 'United States',
        'GB' => 'United Kingdom',
        'CA' => 'Canada',
        'IN' => 'India',
        'NL' => 'Netherlands',
        'AU' => 'Australia',
        'ZA' => 'South Africa',
        'FR' => 'France',
        'DE' => 'Germany',
        'SG' => 'Singapore',
        'SE' => 'Sweden',
        'BR' => 'Brazil',
        'AF' => 'Afghanistan',
        'AX' => 'Ãland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'IO' => 'Brit/Indian Ocean Terr.',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, The Dem. Republic Of',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'CÃ´te D\'Ivore',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Terr.',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard/McDonald Isls.',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea (North)',
        'KR' => 'Korea (South)',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macau',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'MP' => 'N. Mariana Isls.',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome/Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'CS' => 'Serbia and Montenegro',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SK' => 'Slovak Republic',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SH' => 'St. Helena',
        'PM' => 'St. Pierre and Miquelon',
        'VC' => 'St. Vincent and Grenadines',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard/Jan Mayen Isls.',
        'SZ' => 'Swaziland',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks/Caicos Isls.',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'UM' => 'US Minor Outlying Is.',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VA' => 'Vatican City',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands (British)',
        'VI' => 'Virgin Islands (U.S.)',
        'WF' => 'Wallis/Futuna Isls.',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
      ),
    ),
    'title' =>
    array (
      'type' => 'text',
      'displayName' => 'Title',
      'apiName' => 'C_Title',
    ),
    'department' =>
    array (
      'type' => 'select',
      'displayName' => 'Department',
      'apiName' => 'C_Department1',
      'options' =>
      array (
        '' => ' - Select List -',
        'Administration & Support' => 'Administration & Support',
        'Circulation/Fulfillment' => 'Circulation/Fulfillment',
        'Customer Service' => 'Customer Service',
        'Finance' => 'Finance',
        'Human Resources' => 'Human Resources',
        'IT' => 'IT',
        'Legal & Compliance' => 'Legal & Compliance',
        'Marketing' => 'Marketing',
        'Operations' => 'Operations',
        'Sales' => 'Sales',
      ),
    ),
    'jobLevel' =>
    array (
      'type' => 'select',
      'displayName' => 'Job Level',
      'apiName' => 'C_Job_Role1',
      'options' =>
      array (
        '' => ' - Please Select -',
        'CXO' => 'CXO',
        'Board member' => 'Board member',
        'Compliance Officer, Regulator' => 'Compliance Officer, Regulator',
        'Controller' => 'Controller',
        'Consultant' => 'Consultant',
        'Director' => 'Director',
        'Employee' => 'Employee',
        'Investor' => 'Investor',
        'Manager' => 'Manager',
        'Owner' => 'Owner',
        'President' => 'President',
        'Student' => 'Student',
        'Superintendent' => 'Superintendent',
        'SVP, EVP, VP or equivalent' => 'SVP, EVP, VP or equivalent',
        'Volunteer' => 'Volunteer',
      ),
    ),
    'industry' =>
    array (
      'type' => 'select',
      'displayName' => 'Industry',
      'apiName' => 'C_Industry1',
      'options' =>
      array (
        '' => ' - Please Select -',
        'Agriculture' => 'Agriculture',
        'Automotive' => 'Automotive',
        'B2B Magazines and Media' => 'B2B Magazines and Media',
        'Banking' => 'Banking',
        'Biotechnology' => 'Biotechnology',
        'Chemicals' => 'Chemicals',
        'Consumer Magazines and Media' => 'Consumer Magazines and Media',
        'Consumer Products' => 'Consumer Products',
        'Consumer Services' => 'Consumer Services',
        'Direct Marketing' => 'Direct Marketing',
        'Education' => 'Education',
        'Energy' => 'Energy',
        'Entertainment' => 'Entertainment',
        'Finance' => 'Finance',
        'Food & Beverage' => 'Food & Beverage',
        'For Profit Membership/Association' => 'For Profit Membership/Association',
        'Government' => 'Government',
        'Healthcare' => 'Healthcare',
        'Insurance' => 'Insurance',
        'Manufacturing' => 'Manufacturing',
        'Media' => 'Media',
        'Not For Profit' => 'Not For Profit',
        'Not for Profit Membership/Association' => 'Not for Profit Membership/Association',
        'Other' => 'Other',
        'Technology' => 'Technology',
        'Telecommunications' => 'Telecommunications',
        'Travel Tourism' => 'Travel Tourism',
        'Utilities' => 'Utilities',
      ),
    ),
    'companySize' =>
    array (
      'type' => 'select',
      'displayName' => 'Company Size',
      'apiName' => 'C_Company_Size1',
      'options' =>
      array (
        '' => ' - Please Select -',
        '<10M' => '<10M',
        '11M-100M' => '11M-100M',
        '101M-500M ' => '101M-500M ',
        '501M-1B' => '501M-1B',
        '>1B' => '>1B',
      ),
    ),
    'totalCirculation' =>
    array (
      'type' => 'select',
      'displayName' => 'Total Circulation ',
      'apiName' => 'C_Total_Circulation_1',
      'options' =>
      array (
        '0-50,000' => '0-50,000',
        '50,001-100,000' => '50,001-100,000',
        '100,001-500,000' => '100,001-500,000',
        '500,001-1,000,000' => '500,001-1,000,000',
        '1,000,000+' => '1,000,000+',
      ),
    ),
    'typeOfPublisher' =>
    array (
      'type' => 'select',
      'displayName' => 'Type of Publisher',
      'apiName' => 'C_Status1',
      'options' =>
      array (
        'Consumer' => 'Consumer',
        'B2B/Trade' => 'B2B/Trade',
        'Other' => 'Other',
      ),
    ),
    'address1' =>
    array (
      'type' => 'text',
      'displayName' => 'Address 1',
      'apiName' => 'C_Address1',
    ),
    'address2' =>
    array (
      'type' => 'text',
      'displayName' => 'Address 2',
      'apiName' => 'C_Address2',
    ),
    'city' =>
    array (
      'type' => 'text',
      'displayName' => 'City',
      'apiName' => 'C_City',
    ),
    'stateOrProvince' =>
    array (
      'type' => 'select',
      'displayName' => 'State or Province',
      'apiName' => 'C_State_Prov',
      'options' =>
      array (
        '' => ' - Please Select -',
        'AB' => 'AB',
        'AL' => 'AL',
        'AK' => 'AK',
        'AR' => 'AR',
        'AZ' => 'AZ',
        'BC' => 'BC',
        'CA' => 'CA',
        'CO' => 'CO',
        'CT' => 'CT',
        'DC' => 'DC',
        'DE' => 'DE',
        'FL' => 'FL',
        'GA' => 'GA',
        'HI' => 'HI',
        'IA' => 'IA',
        'ID' => 'ID',
        'IL' => 'IL',
        'IN' => 'IN',
        'KS' => 'KS',
        'KY' => 'KY',
        'LA' => 'LA',
        'MA' => 'MA',
        'MB' => 'MB',
        'MD' => 'MD',
        'ME' => 'ME',
        'MI' => 'MI',
        'MN' => 'MN',
        'MO' => 'MO',
        'MS' => 'MS',
        'MT' => 'MT',
        'NB' => 'NB',
        'NC' => 'NC',
        'ND' => 'ND',
        'NE' => 'NE',
        'NH' => 'NH',
        'NJ' => 'NJ',
        'NL' => 'NL',
        'NM' => 'NM',
        'NS' => 'NS',
        'NV' => 'NV',
        'NY' => 'NY',
        'OH' => 'OH',
        'OK' => 'OK',
        'ON' => 'ON',
        'OR' => 'OR',
        'PA' => 'PA',
        'PE' => 'PE',
        'QC' => 'QC',
        'RI' => 'RI',
        'SC' => 'SC',
        'SD' => 'SD',
        'SK' => 'SK',
        'TN' => 'TN',
        'TX' => 'TX',
        'UT' => 'UT',
        'VA' => 'VA',
        'VT' => 'VT',
        'WA' => 'WA',
        'WI' => 'WI',
        'WV' => 'WV',
        'WY' => 'WY',
        'Non U.S.' => 'Non U.S.',
      ),
    ),
    'twitter' =>
    array (
      'type' => 'text',
      'displayName' => 'Twitter',
      'apiName' => 'C_Twitter1',
    ),
    'facebook' =>
    array (
      'type' => 'text',
      'displayName' => 'Facebook',
      'apiName' => 'C_Facebook1',
    ),
    'linkedIn' =>
    array (
      'type' => 'text',
      'displayName' => 'LinkedIn',
      'apiName' => 'C_LinkedIn1',
    ),
    'notForProfitOrganizationType' =>
    array (
      'type' => 'select',
      'displayName' => 'Not for Profit Organization Type',
      'apiName' => 'C_Not_for_Profit_Organization_Type1',
      'options' =>
      array (
        'National' => 'National',
        'Regional' => 'Regional',
        'Local' => 'Local',
      ),
    ),
  ),
  'hidden' =>
  array (
    'elqFormName' => 'cds-global-resources',
    'elqSiteId' => '1851',
    'elqCampaignId' => '',
  ),
  'admin' =>
  array (
    'elqSource' =>
    array (
      'type' => 'text',
      'displayName' => 'Eloqua Asset Name',
      'displayValue'  =>  '',
    ),
    'LeadSource' =>
    array (
        'type' => 'select',
        'displayName' => 'Eloqua Lead Source',
        'displayValue'  =>  '',
        'options' =>
        array (
            'Marketing_Campaign_Case_Study' => 'Case Study',
            'Marketing_Campaign_Seminar' => 'Seminar',
            'Marketing_Campaign_Webinar' => 'Webinar',
            'Marketing_Campaign_White_Paper' =>  'White Paper',
            'Inbound_Contact_Me_form_Web' => 'Inbound Contact Me Form',
            'Inbound_Email' => 'Inbound Email',
            'Inbound_Phone_call' => 'Inbound Phone Call',
        ),
    ),
    'LeadSourceName' =>
    array (
      'type' => 'text',
      'displayName' => 'Eloqua Source Name',
      'displayValue'  =>  'CDS-Global.com',
    ),
    'LSMostRecent' =>
    array (
      'type' => 'select',
      'displayName' => 'Eloqua Lead Source Most Recent',
      'displayValue'  =>  '',
      'options' =>
        array (
            'Marketing_Campaign_Case_Study' => 'Case Study',
            'Marketing_Campaign_Seminar' => 'Seminar',
            'Marketing_Campaign_Webinar' => 'Webinar',
            'Marketing_Campaign_White_Paper' =>  'White Paper',
            'Inbound_Contact_Me_form_Web' => 'Inbound Contact Me Form',
            'Inbound_Email' => 'Inbound Email',
            'Inbound_Phone_call' => 'Inbound Phone Call',
        ),
    ),
    'LSNameMostRecent' =>
    array (
      'type' => 'text',
      'displayName' => 'Eloqua Lead Source Most Recent Name',
      'displayValue'  =>  'CDS-Global.com',
    ),
  ),
  'qs' =>
  array (
    'elqCampaignName' => 'cn',
    'elqMed' => 'utm_medium',
    'eLQInitialCampaignName1' => '',
  ),
);
